name: Continuous Deployment
 
on: 
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/forum_api_starter_project
          git pull origin main
          npm install
          npm run migrate up
          pm2 start npm --name "forum_api_starter_project" -- run "start"